apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: yas
    namespace: argocd

spec:
    generators:
        - matrix:
              generators:
                  - list:
                        elements:
                            - service: yas-configuration
                            - service: storefront-ui
                            - service: storefront-bff
                            # - service: product
                            # - service: sampledata
                            # - service: media
                            # - service: backoffice-ui
                            # - service: backoffice-bff
                            # - service: cart
                            # - service: customer
                            # - service: inventory
                            # - service: location
                            # - service: order
                            # - service: payment
                            # - service: payment-paypal
                            # - service: promotion
                            # - service: rating
                            # - service: recommendation
                            # - service: search
                            # - service: tax
                            # - service: webhook
                  - list:
                        elements:
                            - env: dev
                            # - env: staging

    template:
        metadata:
            name: "{{service}}-{{env}}"

        spec:
            project: default

            sources:
                - repoURL: https://github.com/hoanggiabao1804/demo-lab01-devops.git
                  targetRevision: HEAD
                  path: k8s/charts/{{service}}

                  helm:
                      valueFiles:
                          - $values/{{env}}/{{service}}-values.yaml

                - repoURL: https://github.com/hoanggiabao1804/yas-helmchart-k8s.git
                  targetRevision: HEAD
                  ref: values

            destination:
                server: https://kubernetes.default.svc
                namespace: "{{env}}"

            syncPolicy:
                syncOptions:
                    - CreateNamespace=true
                automated:
                    prune: true
                    selfHeal: true
