backend:
  image:
    repository: 23120022/yas-storefront-bff
    tag: test1
  nameOverride: storefront-bff
  fullnameOverride: storefront-bff
  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,storefront-bff-extra-configmap"
  ingress:
    enabled: false
    # enabled: true
    # host: dev.storefront.yas.local.com
    # path: /
  extraObjects:
    - apiVersion: networking.istio.io/v1
      kind: Gateway
      metadata:
        name: storefront-gateway
        namespace: dev
      spec:
        selector:
          istio: ingressgateway
        servers:
          - port:
              number: 80
              name: http
              protocol: HTTP
            hosts:
              - dev.storefront.yas.local.com
              - api.yas.local.com
              - identity.yas.local.com

    - apiVersion: networking.istio.io/v1
      kind: VirtualService
      metadata:
        name: storefront-bff
        namespace: dev
      spec:
        hosts:
          - dev.storefront.yas.local.com
        gateways:
          - storefront-gateway
        http:
          - match:
              - uri:
                  prefix: /
            route:
              - destination:
                  host: storefront-bff.dev.svc.cluster.local
                  port:
                    number: 80
    - apiVersion: networking.istio.io/v1
      kind: VirtualService
      metadata:
        name: api-media
        namespace: dev
      spec:
        hosts:
          - api.yas.local.com
        gateways:
          - storefront-gateway
        http:
          - match:
              - uri:
                  prefix: /media
            route:
              - destination:
                  host: media.dev.svc.cluster.local
                  port:
                    number: 80
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://storefront-ui:3000
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret
  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: storefront-bff-extra-config
      configMap:
        name: storefront-bff-extra-configmap
  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: storefront-bff-extra-config
      mountPath: /opt/yas/extra-config
  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/storefront-bff-extra-config.yaml
